# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586e9bf6ab9c117f53ce53d196548dd72b6b6f1f4670eabf2de4d82fe020a6f579d71bfac5ee36e1b8253eb0bd71f21a8844d2822b511b0602b20288106fe069

test:
  secret_key_base: d0edb22d189a836c0e2d589b165cfc78182c8b1cad02d6877624fbba4e1d117771fca33262417f544a87c3b34f8a58e1febe9d3d7425e578e08ba0850a712af8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
